[project]
name = "progetto-prova"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "nba-api>=1.6.1",
    "pandas>=2.2.3",
    "streamlit>=1.41.1",
]
